spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: dev

#服务地址
server:
  context-path: /sell

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: sunquan
---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: